name: Run rhods-disconnected-install-helper script every 5 minutes

on: 
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - feature/search-quay-images

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Run rhods_disconnected_install_helper.sh script
      run: ./rhods_disconnected_install_helper.sh
      shell: bash