name: Run rhoai-disconnected-helper z stream

on: 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run rhoai-disconnected-helper-z-stream.sh script
      run: |
        chmod +x rhoai-disconnected-helper-z-stream.sh
        chmod +x rhoai-dih.sh
        ./rhoai-disconnected-helper-z-stream.sh "${{ github.event.inputs.input_variable1 }}" "${{ github.event.inputs.input_variable2 }}"
      env:
          INPUT_GIT_BRANCH: ${{ github.event.inputs.input_variable1 }}
          INPUT_GIT_VERSION: ${{ github.event.inputs.input_variable2 }}
      shell: bash
    - name: Commit and push changes to main branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update rhoai-disconnected-helper.sh script"
        repository: red-hat-data-services/rhoai-disconnected-install-helper
