name: Run rhods-disconnected-install-helper script every 5 minutes

on: 
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - feature/search-quay-images

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run rhods_disconnected_install_helper.sh script
      run: |
        chmod +x rhods_disconnected_install_helper.sh
        ./rhods_disconnected_install_helper.sh
      shell: bash
    - name: Commit changes using github_token {{ secret.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update rhods_disconnected_install_helper.sh"
        git push
    - name: Commit & Push changes to feature/search-quay-images branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: feature/search-quay-images
        repository: https://github.com/pablofelix/rhods-disconnected-install-helper
