name: Run rhods-disconnected-install-helper script every 5 minutes

on: 
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  run-rhods-disconnected-install-helper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run run-rhods-disconnected-install-helper script
      run: ./rhods-disconnected-install-helper.sh