name: Run rhods-disconnected-install-helper script once a day

on: 
  schedule:
    - cron:  '0 12 * * *'
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Runrhods-disconnected-helper.sh script
      run: |
        chmod +xrhods-disconnected-helper.sh
        ./rhods_disconnected_install_helper.sh
      shell: bash
    - name: Commit and push changes to main branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Updaterhods-disconnected-helper.sh script"
        repository: red-hat-data-services/rhods-disconnected-install-helper
